name: Code quality

on:
  pull_request:
    branches:
      - master
      - main
      - staging
  push:
    branches:
      - main
      - master

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install
      - run: pnpm biome ci